### PR TITLE
Adjust to https://github.com/homalg-project/CAP_project/pull/665

### PR DESCRIPTION
**Pull request by zickgraf**

### CODE REVIEW

**Comment by zickgraf** [comment]
Note that I have hardcoded the operation `MorphismBetweenDirectSums` at one point. This is probably not the best solution, but it works (hopefully :D).

**Comment by zickgraf** [comment]
The CI is still failing, and I'm a bit out of ideas because I cannot reproduce the failure locally. @kamalsaleh Could you try and see if the tests run fine or fail on your computer when checking out this PR?

**Comment by kamalsaleh** [comment]
I have already adjusted the code to add `MorphismBetweenDirectSums` with five arguments. Do you know why the Github action is "Queued"?

**Comment by kamalsaleh** [comment]
https://www.githubstatus.com/

**Comment by zickgraf** [comment]
> https://www.githubstatus.com/

Exactly, looks like GitHub is having issues again :-(

**Pull request merged**
