### PR TITLE
Adjust to https://github.com/homalg-project/CAP_project/pull/649

### PR DESCRIPTION
**Pull request by zickgraf**
Only a subset of the changes are needed for compatibility with the CAP PR, but I decided to update all method records anyway. Note that MorphismBetweenStandardConeObjectsWithGivenObjects cannot get the category as the first argument as GAP does not allow operations with more than six arguments :-(

### CODE REVIEW

**Comment by kamalsaleh** [comment]
> Note that MorphismBetweenStandardConeObjectsWithGivenObjects cannot get the category as the first argument as GAP does not allow operations with more than six arguments :-(

Would this lead to errors or unexpected behavior? If yes, I can adjust the argument list to `"object", "list_of_morphisms", "object"`.

**Comment by zickgraf** [comment]
> Would this lead to errors or unexpected behavior?

No, currently this case is still officially supported. This might change in the future, but until then we might have come across this issue in other contexts and might have fixed this more generically, so there certainly is no need for immediate action :-)

**Comment by zickgraf** [comment]
This PR is now ready for review, too, and has to be merged with failing CI due to the dependency cycle with `Toposes`.

**Comment by kamalsaleh** [comment]
Thank you @zickgraf

**Pull request merged**
