### PR TITLE
reactivate testing notebooks

### PR DESCRIPTION
**Pull request by kamalsaleh**

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
Very nice.

**Comment by mohamed-barakat** [comment]
Could you please bump the version of the affected packages?

**Comment by kamalsaleh** [comment]
This pr also bumps the versions and new releases are already created.

**Comment by mohamed-barakat** [comment]
I see, I expected the version bumps in the commit where you have updated the notebooks :)

At some point, you could also bump the dependencies. This is of course easier when done incrementally.

**Pull request merged**
